name: release

on:
  push:
    branches:
      - main
        
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: dotnet setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: test
        run: dotnet test
      - name: pack
        run: dotnet pack --configuration Release --output out/
      - name: push to nuget
        run: dotnet nuget push ./out/HumanRegexBuilder.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_KEY} --skip-duplicate
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      
